// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBe2fK_lPmH7Xh1MvUgXB80ywtH_y8oUI',
    appId: '1:113245347636:web:f9b0b80cfe16be640bcf61',
    messagingSenderId: '113245347636',
    projectId: 'travelapp-53000',
    authDomain: 'travelapp-53000.firebaseapp.com',
    storageBucket: 'travelapp-53000.appspot.com',
    measurementId: 'G-W275QTKXM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_FD2TSUM5tW2CND5sTl4Jyw--aEpB0g',
    appId: '1:113245347636:android:2d840b90aec289fa0bcf61',
    messagingSenderId: '113245347636',
    projectId: 'travelapp-53000',
    storageBucket: 'travelapp-53000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jvH1Op2ILP-JLhPFqefwwbGMAnRJO14',
    appId: '1:113245347636:ios:77e455d4158f43220bcf61',
    messagingSenderId: '113245347636',
    projectId: 'travelapp-53000',
    storageBucket: 'travelapp-53000.appspot.com',
    iosBundleId: 'com.example.tripmakerflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jvH1Op2ILP-JLhPFqefwwbGMAnRJO14',
    appId: '1:113245347636:ios:6c48a4a926f4002f0bcf61',
    messagingSenderId: '113245347636',
    projectId: 'travelapp-53000',
    storageBucket: 'travelapp-53000.appspot.com',
    iosBundleId: 'com.example.tripmakerflutterapp.RunnerTests',
  );
}
